[package]
name = "hts_connector"
version = "0.1.0"
edition = "2021"

[dependencies]
influxdb = "0.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
envconfig = "0.10.0"
dotenv = "0.15.0"
log = "0.4.14"
env_logger = "0.9.0"