[env]
RUSTFLAGS = "-A dead_code" 

[tasks.test]
command = "cargo"
args = [
    "test",
    "--all-targets",
    "--",
]

[tasks.test-sensitive]
command = "cargo"
args = [
    "test",
    "--all-targets",
    "--",
    "--ignored",
    "--test-threads=1"
]

[tasks.test-debug]
command = "cargo"
args = [
    "test",
    "--all-targets",
    "--",
    "--nocapture"
]

[tasks.lint]
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "--",
    "-D", "warnings",
    "-A", "dead_code"
]

[tasks.build]
command = "cargo"
args = [
    "build",
]

[tasks.build-release]
command = "cargo"
args = [
    "build",
    "--release"
]