[env]
RUSTFLAGS = "-A dead_code" 

[tasks.test]
command = "cargo"
args = [
    "test",
    "--all-targets",
    "--",
]

[tasks.test-sensitive]
command = "cargo"
args = [
    "test",
    "--all-targets",
    "--",
    "--ignored",
    "--test-threads=1"
]

[tasks.test-debug]
command = "cargo"
args = [
    "test",
    "--all-targets",
    "--",
    "--nocapture"
]

[tasks.lint]
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "--",
    "-D", "warnings",
    "-D", "clippy::all",
    "-D", "clippy::nursery",
    "-D", "clippy::unwrap_used",
    "-D", "clippy::panic",
    "-D", "clippy::print_stderr",
    "-D", "clippy::complexity",
    "-D", "clippy::correctness",
    "-D", "clippy::style",
    "-D", "clippy::perf",
    "-A", "clippy::missing_panics_doc",
    "-A", "dead_code"
]

[tasks.fmt]
command = "cargo"
args = [
    "fmt"
]

[tasks.build]
command = "cargo"
args = [
    "build",
]

[tasks.release]
command = "cargo"
args = [
    "build",
    "--release"
]