name: CD

on:
  push:
    tags:
      - v*
    branches:
      - chore/cd

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry- 

      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Build project
        run: make build-release

      - name: Upload Release Asset (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: hts-connector.exe
          path: ./target/release/hts_connector.exe

      - name: Upload Release Asset (Ubuntu)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: hts-connector
          path: ./target/release/hts_connector